apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
  namespace: nsm
  labels:
    role: nids
spec:
  selector:
    matchLabels:
      name: suricata
  template:
    metadata:
      labels:
        name: suricata
    spec:
      containers:
      - name: suricata
        image: 192.168.136.134:32000/suricata:0.1
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_NICE
        volumeMounts:
        - name: suricata-logs
          mountPath: /var/log/suricata/  
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.5.2
        args: [
          "--strict.perms=false",
          "-c", "/etc/filebeat/filebeat.yml",
          "-e",
        ]
        env:
        - name: LOGSTASH_HOST
          value: logstash
        - name: LOGSTASH_PORT
          value: "5044"
        - name: SENSOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        volumeMounts:
        - name: filebeat-config
          mountPath: /etc/filebeat/
          readOnly: true
        - name: suricata-logs
          mountPath: /var/log/suricata
      nodeSelector:
        type: net-sensor
      hostNetwork: true
      
      volumes:
      - name: suricata-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config
          defaultMode: 0666
